languageCode = "en-us"
title = "Potatso Manual"
baseURL = "https://manual-beta.potatso.com/"
theme = "hugo-material-docs"
googleAnalytics = "UA-38012898-7"

[params]
	# General information
	author = "Potatso"
	description = "The ultimate networking tool for iOS."
	copyright = "potatso.com"

	version = "2.0.0"
	logo = "images/logo.png"
	favicon = "images/favicon.ico"

	permalink = "#"

    showFooterNav = true

	custom_css = [
		"css/custom.css"
	]

	[params.palette]
    	primary = "pink"
    	accent  = "teal"

    [params.font]
        text = "Roboto"
        code = "Roboto Mono"

# [[menu.main]]
# 	name   = "Potatso"
# 	url    = "/"
# 	weight = 0

[[menu.main]]
	name   = "开始使用"
	url    = "get-started/"
	weight = 10

[[menu.main]]
	name   = "高级"
	url    = "advanced/"
	weight = 20

[[menu.main]]
	name   = "PCF"
	url    = "pcf/"
	weight = 30

[[menu.main]]
	name   = "路线图"
	url    = "roadmap/"
	weight = 40

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[social]
  twitter = "PotatsoApp"
  github  = "Potatso/Manual"
